#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_func = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_if = 7,
  anon_sym_el = 8,
  anon_sym_DASH = 9,
  anon_sym_SLASH = 10,
  anon_sym_STAR = 11,
  anon_sym_PERCENT = 12,
  anon_sym_PLUS = 13,
  anon_sym_CARET = 14,
  anon_sym_PIPE = 15,
  anon_sym_AMP = 16,
  anon_sym_EQ_EQ = 17,
  anon_sym_BANG_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_GT = 21,
  anon_sym_GT_EQ = 22,
  anon_sym_EQ = 23,
  anon_sym_var = 24,
  anon_sym_DOT_DOT = 25,
  sym_string = 26,
  sym_integer = 27,
  sym_hex_integer = 28,
  sym_bin_integer = 29,
  sym_boolean = 30,
  sym_statement_end = 31,
  sym_identifier = 32,
  sym_source_file = 33,
  sym_function_definition = 34,
  sym_statement = 35,
  sym_block = 36,
  sym_ifelse = 37,
  sym_expression = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_function_definition_repeat1 = 40,
  aux_sym_block_repeat1 = 41,
  aux_sym_ifelse_repeat1 = 42,
  aux_sym_expression_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_el] = "el",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_CARET] = "^",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ] = "=",
  [anon_sym_var] = "var",
  [anon_sym_DOT_DOT] = "..",
  [sym_string] = "string",
  [sym_integer] = "integer",
  [sym_hex_integer] = "hex_integer",
  [sym_bin_integer] = "bin_integer",
  [sym_boolean] = "boolean",
  [sym_statement_end] = "statement_end",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_function_definition] = "function_definition",
  [sym_statement] = "statement",
  [sym_block] = "block",
  [sym_ifelse] = "ifelse",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_ifelse_repeat1] = "ifelse_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_el] = anon_sym_el,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_string] = sym_string,
  [sym_integer] = sym_integer,
  [sym_hex_integer] = sym_hex_integer,
  [sym_bin_integer] = sym_bin_integer,
  [sym_boolean] = sym_boolean,
  [sym_statement_end] = sym_statement_end,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_function_definition] = sym_function_definition,
  [sym_statement] = sym_statement,
  [sym_block] = sym_block,
  [sym_ifelse] = sym_ifelse,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_ifelse_repeat1] = aux_sym_ifelse_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_el] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_end] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ifelse] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ifelse_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 5,
  [8] = 8,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 8,
  [14] = 8,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 33,
  [40] = 37,
  [41] = 41,
  [42] = 38,
  [43] = 43,
  [44] = 34,
  [45] = 35,
  [46] = 41,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 43,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 48,
  [55] = 55,
  [56] = 56,
  [57] = 47,
  [58] = 48,
  [59] = 59,
  [60] = 60,
  [61] = 48,
  [62] = 60,
  [63] = 53,
  [64] = 47,
  [65] = 52,
  [66] = 51,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 73,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 78,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 86,
  [90] = 90,
  [91] = 91,
  [92] = 84,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 96,
  [98] = 93,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 110,
  [112] = 109,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '%') ADVANCE(27);
      if (lookahead == '&') ADVANCE(31);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ',') ADVANCE(18);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == ';') ADVANCE(47);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '^') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead == 'v') ADVANCE(50);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '|') ADVANCE(30);
      if (lookahead == '}') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead == 'v') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == ';') ADVANCE(47);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead == 'v') ADVANCE(50);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == ';') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead == 'v') ADVANCE(50);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(4);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ')') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(45);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == ';') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead == 'v') ADVANCE(50);
      if (lookahead == '{') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_el);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == 'b') ADVANCE(12);
      if (lookahead == 'x') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_hex_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_bin_integer);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_boolean);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_statement_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead == 'u') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 14},
  [53] = {.lex_state = 14},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 14},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 14},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 8},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 8},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 8},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 8},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_el] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_hex_integer] = ACTIONS(1),
    [sym_bin_integer] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_statement_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(107),
    [sym_function_definition] = STATE(3),
    [sym_statement] = STATE(3),
    [sym_block] = STATE(60),
    [sym_ifelse] = STATE(60),
    [sym_expression] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_func] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_var] = ACTIONS(15),
    [sym_string] = ACTIONS(17),
    [sym_integer] = ACTIONS(19),
    [sym_hex_integer] = ACTIONS(17),
    [sym_bin_integer] = ACTIONS(17),
    [sym_boolean] = ACTIONS(21),
    [sym_statement_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_func,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(38), 1,
      anon_sym_if,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(44), 1,
      anon_sym_var,
    ACTIONS(50), 1,
      sym_integer,
    ACTIONS(53), 1,
      sym_boolean,
    ACTIONS(56), 1,
      sym_statement_end,
    ACTIONS(59), 1,
      sym_identifier,
    STATE(40), 1,
      sym_expression,
    STATE(60), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(47), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
    STATE(2), 3,
      sym_function_definition,
      sym_statement,
      aux_sym_source_file_repeat1,
  [51] = 15,
    ACTIONS(5), 1,
      anon_sym_func,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(23), 1,
      sym_statement_end,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      sym_expression,
    STATE(60), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
    STATE(2), 3,
      sym_function_definition,
      sym_statement,
      aux_sym_source_file_repeat1,
  [102] = 4,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(68), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(66), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [130] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    STATE(37), 1,
      sym_expression,
    STATE(10), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [177] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(10), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [224] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(10), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [271] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(7), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [318] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(10), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [365] = 14,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      anon_sym_if,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(102), 1,
      anon_sym_var,
    ACTIONS(108), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_boolean,
    ACTIONS(114), 1,
      sym_statement_end,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(37), 1,
      sym_expression,
    STATE(10), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(105), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [412] = 3,
    ACTIONS(120), 1,
      anon_sym_DOT_DOT,
    ACTIONS(68), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(66), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [437] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [484] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(9), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [531] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      sym_statement_end,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_expression,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(62), 2,
      sym_block,
      sym_ifelse,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [578] = 2,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(128), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [600] = 2,
    ACTIONS(134), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [622] = 2,
    ACTIONS(138), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(136), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [644] = 2,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(140), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [666] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(136), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_statement_end,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [702] = 4,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(140), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [728] = 5,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(140), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_statement_end,
  [756] = 6,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(140), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_statement_end,
  [786] = 8,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(140), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_statement_end,
  [820] = 7,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(140), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_CARET,
      anon_sym_PIPE,
      sym_statement_end,
  [852] = 2,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(140), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [874] = 3,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(140), 12,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [898] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(140), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_statement_end,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [934] = 11,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_expression_repeat1,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [974] = 2,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(140), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [996] = 2,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(140), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [1018] = 2,
    ACTIONS(68), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(66), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_CARET,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_statement_end,
  [1040] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(164), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1075] = 4,
    ACTIONS(170), 1,
      anon_sym_el,
    STATE(35), 1,
      aux_sym_ifelse_repeat1,
    ACTIONS(168), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(166), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1100] = 4,
    ACTIONS(176), 1,
      anon_sym_el,
    STATE(34), 1,
      aux_sym_ifelse_repeat1,
    ACTIONS(174), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(172), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1125] = 4,
    ACTIONS(183), 1,
      anon_sym_el,
    STATE(34), 1,
      aux_sym_ifelse_repeat1,
    ACTIONS(181), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(179), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1150] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1184] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(187), 1,
      sym_statement_end,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1218] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1252] = 4,
    ACTIONS(191), 1,
      anon_sym_el,
    STATE(45), 1,
      aux_sym_ifelse_repeat1,
    ACTIONS(168), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(166), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1276] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(193), 1,
      sym_statement_end,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1310] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1344] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1378] = 2,
    ACTIONS(201), 7,
      anon_sym_func,
      anon_sym_if,
      anon_sym_el,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(199), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1398] = 4,
    ACTIONS(203), 1,
      anon_sym_el,
    STATE(44), 1,
      aux_sym_ifelse_repeat1,
    ACTIONS(174), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(172), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1422] = 4,
    ACTIONS(206), 1,
      anon_sym_el,
    STATE(44), 1,
      aux_sym_ifelse_repeat1,
    ACTIONS(181), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(179), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1446] = 9,
    ACTIONS(148), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(152), 1,
      anon_sym_AMP,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 3,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1480] = 2,
    ACTIONS(212), 7,
      anon_sym_func,
      anon_sym_if,
      anon_sym_el,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1500] = 2,
    ACTIONS(216), 7,
      anon_sym_func,
      anon_sym_if,
      anon_sym_el,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(214), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1520] = 2,
    ACTIONS(212), 6,
      anon_sym_if,
      anon_sym_el,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1539] = 2,
    ACTIONS(201), 6,
      anon_sym_if,
      anon_sym_el,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(199), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1558] = 2,
    ACTIONS(220), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(218), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1577] = 2,
    ACTIONS(224), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(222), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1596] = 2,
    ACTIONS(228), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(226), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1615] = 2,
    ACTIONS(216), 6,
      anon_sym_if,
      anon_sym_el,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(214), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1634] = 2,
    ACTIONS(232), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(230), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1653] = 2,
    ACTIONS(236), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(234), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1672] = 2,
    ACTIONS(212), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1691] = 2,
    ACTIONS(216), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(214), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1710] = 2,
    ACTIONS(240), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(238), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1729] = 2,
    ACTIONS(244), 6,
      anon_sym_func,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(242), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1748] = 2,
    ACTIONS(216), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(214), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1766] = 2,
    ACTIONS(244), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(242), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1784] = 2,
    ACTIONS(228), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(226), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1802] = 2,
    ACTIONS(212), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1820] = 2,
    ACTIONS(224), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(222), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1838] = 2,
    ACTIONS(220), 5,
      anon_sym_if,
      anon_sym_var,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(218), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
      sym_statement_end,
  [1856] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [1886] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(23), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [1913] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(19), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [1940] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(24), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [1967] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(22), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [1994] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(21), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2021] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(46), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2048] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(32), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2075] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(20), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2102] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(41), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2129] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(26), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2156] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(42), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2183] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(36), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2210] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(25), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2237] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(15), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2264] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(27), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2291] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(21), 1,
      sym_boolean,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(38), 1,
      sym_expression,
    ACTIONS(17), 3,
      sym_string,
      sym_hex_integer,
      sym_bin_integer,
  [2318] = 3,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_block,
  [2328] = 3,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_function_definition_repeat1,
  [2338] = 3,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(66), 1,
      sym_block,
  [2348] = 3,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_function_definition_repeat1,
  [2358] = 3,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_expression_repeat1,
  [2368] = 3,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
    STATE(51), 1,
      sym_block,
  [2378] = 3,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_expression_repeat1,
  [2388] = 3,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_function_definition_repeat1,
  [2398] = 3,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      sym_block,
  [2408] = 2,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_block,
  [2415] = 2,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      sym_identifier,
  [2422] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym_block,
  [2429] = 2,
    ACTIONS(274), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
  [2436] = 2,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
  [2443] = 2,
    ACTIONS(274), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_block,
  [2450] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_block,
  [2457] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_block,
  [2464] = 1,
    ACTIONS(257), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2469] = 1,
    ACTIONS(276), 1,
      sym_identifier,
  [2473] = 1,
    ACTIONS(278), 1,
      sym_integer,
  [2477] = 1,
    ACTIONS(280), 1,
      anon_sym_EQ,
  [2481] = 1,
    ACTIONS(282), 1,
      sym_identifier,
  [2485] = 1,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
  [2489] = 1,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
  [2493] = 1,
    ACTIONS(288), 1,
      sym_identifier,
  [2497] = 1,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
  [2501] = 1,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
  [2505] = 1,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
  [2509] = 1,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 130,
  [SMALL_STATE(6)] = 177,
  [SMALL_STATE(7)] = 224,
  [SMALL_STATE(8)] = 271,
  [SMALL_STATE(9)] = 318,
  [SMALL_STATE(10)] = 365,
  [SMALL_STATE(11)] = 412,
  [SMALL_STATE(12)] = 437,
  [SMALL_STATE(13)] = 484,
  [SMALL_STATE(14)] = 531,
  [SMALL_STATE(15)] = 578,
  [SMALL_STATE(16)] = 600,
  [SMALL_STATE(17)] = 622,
  [SMALL_STATE(18)] = 644,
  [SMALL_STATE(19)] = 666,
  [SMALL_STATE(20)] = 702,
  [SMALL_STATE(21)] = 728,
  [SMALL_STATE(22)] = 756,
  [SMALL_STATE(23)] = 786,
  [SMALL_STATE(24)] = 820,
  [SMALL_STATE(25)] = 852,
  [SMALL_STATE(26)] = 874,
  [SMALL_STATE(27)] = 898,
  [SMALL_STATE(28)] = 934,
  [SMALL_STATE(29)] = 974,
  [SMALL_STATE(30)] = 996,
  [SMALL_STATE(31)] = 1018,
  [SMALL_STATE(32)] = 1040,
  [SMALL_STATE(33)] = 1075,
  [SMALL_STATE(34)] = 1100,
  [SMALL_STATE(35)] = 1125,
  [SMALL_STATE(36)] = 1150,
  [SMALL_STATE(37)] = 1184,
  [SMALL_STATE(38)] = 1218,
  [SMALL_STATE(39)] = 1252,
  [SMALL_STATE(40)] = 1276,
  [SMALL_STATE(41)] = 1310,
  [SMALL_STATE(42)] = 1344,
  [SMALL_STATE(43)] = 1378,
  [SMALL_STATE(44)] = 1398,
  [SMALL_STATE(45)] = 1422,
  [SMALL_STATE(46)] = 1446,
  [SMALL_STATE(47)] = 1480,
  [SMALL_STATE(48)] = 1500,
  [SMALL_STATE(49)] = 1520,
  [SMALL_STATE(50)] = 1539,
  [SMALL_STATE(51)] = 1558,
  [SMALL_STATE(52)] = 1577,
  [SMALL_STATE(53)] = 1596,
  [SMALL_STATE(54)] = 1615,
  [SMALL_STATE(55)] = 1634,
  [SMALL_STATE(56)] = 1653,
  [SMALL_STATE(57)] = 1672,
  [SMALL_STATE(58)] = 1691,
  [SMALL_STATE(59)] = 1710,
  [SMALL_STATE(60)] = 1729,
  [SMALL_STATE(61)] = 1748,
  [SMALL_STATE(62)] = 1766,
  [SMALL_STATE(63)] = 1784,
  [SMALL_STATE(64)] = 1802,
  [SMALL_STATE(65)] = 1820,
  [SMALL_STATE(66)] = 1838,
  [SMALL_STATE(67)] = 1856,
  [SMALL_STATE(68)] = 1886,
  [SMALL_STATE(69)] = 1913,
  [SMALL_STATE(70)] = 1940,
  [SMALL_STATE(71)] = 1967,
  [SMALL_STATE(72)] = 1994,
  [SMALL_STATE(73)] = 2021,
  [SMALL_STATE(74)] = 2048,
  [SMALL_STATE(75)] = 2075,
  [SMALL_STATE(76)] = 2102,
  [SMALL_STATE(77)] = 2129,
  [SMALL_STATE(78)] = 2156,
  [SMALL_STATE(79)] = 2183,
  [SMALL_STATE(80)] = 2210,
  [SMALL_STATE(81)] = 2237,
  [SMALL_STATE(82)] = 2264,
  [SMALL_STATE(83)] = 2291,
  [SMALL_STATE(84)] = 2318,
  [SMALL_STATE(85)] = 2328,
  [SMALL_STATE(86)] = 2338,
  [SMALL_STATE(87)] = 2348,
  [SMALL_STATE(88)] = 2358,
  [SMALL_STATE(89)] = 2368,
  [SMALL_STATE(90)] = 2378,
  [SMALL_STATE(91)] = 2388,
  [SMALL_STATE(92)] = 2398,
  [SMALL_STATE(93)] = 2408,
  [SMALL_STATE(94)] = 2415,
  [SMALL_STATE(95)] = 2422,
  [SMALL_STATE(96)] = 2429,
  [SMALL_STATE(97)] = 2436,
  [SMALL_STATE(98)] = 2443,
  [SMALL_STATE(99)] = 2450,
  [SMALL_STATE(100)] = 2457,
  [SMALL_STATE(101)] = 2464,
  [SMALL_STATE(102)] = 2469,
  [SMALL_STATE(103)] = 2473,
  [SMALL_STATE(104)] = 2477,
  [SMALL_STATE(105)] = 2481,
  [SMALL_STATE(106)] = 2485,
  [SMALL_STATE(107)] = 2489,
  [SMALL_STATE(108)] = 2493,
  [SMALL_STATE(109)] = 2497,
  [SMALL_STATE(110)] = 2501,
  [SMALL_STATE(111)] = 2505,
  [SMALL_STATE(112)] = 2509,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(105),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(79),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(81),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(108),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(79),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(14),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(112),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(81),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(108),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(31),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(11),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(31),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(62),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(4),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 5),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifelse, 5),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifelse, 5),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ifelse_repeat1, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ifelse_repeat1, 2),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ifelse_repeat1, 2), SHIFT_REPEAT(110),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifelse, 6),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifelse, 6),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ifelse_repeat1, 5),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ifelse_repeat1, 5),
  [203] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ifelse_repeat1, 2), SHIFT_REPEAT(111),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifelse, 8),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifelse, 8),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifelse, 7),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifelse, 7),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2), SHIFT_REPEAT(102),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(74),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [286] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_reimu() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
